### ISSUE TITLE
NullPointerException when writing out jobs for a future year

### ISSUE THREAD

**Issue by dziemke** [msmobility/silo#134]
Seems that the job or its zone cannot be found when running SILO MUC. Seems to be related to some fo the latest changes regarding locations/coordinates...

2019-01-22 16:14:53,506  WARN IssueCounter:99   Encountered 89 cases where couple wanted to get divorced but could not find vacant dwelling.
2019-01-22 16:14:53,506  WARN IssueCounter:103   Encountered 110 cases where child wanted to leave parental household but could not find vacant dwelling.
2019-01-22 16:14:53,508  INFO SiloModel:281   Finished this simulation period with 4418894 persons, 2116358 households and 2232140 dwellings.
2019-01-22 16:14:53,507  WARN IssueCounter:105   Encountered 1 cases where a couple wanted to marry (cohabitate) but could not find vacant dwelling.
2019-01-22 16:14:53,508  WARN IssueCounter:107   Encountered 18 cases where a household had to outmigrate because its dwelling was demolished and no other vacant dwelling could be found.
2019-01-22 16:14:53,511  INFO SummarizeData:476   Writing household file to ./microData/futureYears/hh_2012.csv
2019-01-22 16:14:54,464  INFO SummarizeData:506   Writing person file to ./microData/futureYears/pp_2012.csv
2019-01-22 16:14:54,464 ERROR SiloModel:85 Error running SILO.
2019-01-22 16:14:54,465  INFO SiloUtil:1037 Runtime: 0 hours and 3 minutes.
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at de.tum.bgu.msm.SiloModel.runModel(SiloModel.java:86)
	at run.SiloMuc.main(SiloMuc.java:32)
Caused by: java.lang.NullPointerException
	at de.tum.bgu.msm.data.SummarizeData.writePersons(SummarizeData.java:566)
	at de.tum.bgu.msm.data.SummarizeData.writeOutSyntheticPopulation(SummarizeData.java:407)
	at de.tum.bgu.msm.SiloModel.endSimulation(SiloModel.java:298)
	at de.tum.bgu.msm.SiloModel.runModel(SiloModel.java:83)
	... 1 more

**Comment by nkuehnel** [comment]
Strange, seems like a person references to a job that is no longer existent.

Could you provide me with the properties file that you used? Did you run it with input files from the gitlab repo?
