### ISSUE TITLE
java.lang.ClassCastException in Synthetic population generator for Maryland

### ISSUE THREAD

**Issue by mhchayan** [msmobility/silo#307]
Hi,
I was trying to run the Synthetic population for Maryland from "synthetic-population\src\main\java\de\tum\bgu\msm\syntheticPopulationGenerator\maryland\SyntheticPopUs.java". While I gave input of PUMS data, it shows the following error for person data. 

java.lang.ClassCastException: de.tum.bgu.msm.data.person.PersonImpl cannot be cast to de.tum.bgu.msm.data.person.PersonMstm
2020-06-29 01:35:07,165  INFO SyntheticPopUs:540 Created 0 persons.
	at de.tum.bgu.msm.syntheticPopulationGenerator.maryland.SyntheticPopUs.readPersons(SyntheticPopUs.java:528)
	at de.tum.bgu.msm.syntheticPopulationGenerator.maryland.SyntheticPopUs.processPums(SyntheticPopUs.java:305)
	at de.tum.bgu.msm.syntheticPopulationGenerator.maryland.SyntheticPopUs.runSP(SyntheticPopUs.java:125)
	at de.tum.bgu.msm.syntheticPopulationGenerator.maryland.RunSyntheticPopUs.main(RunSyntheticPopUs.java:26)

How to solve this problem? I appreciate your help. Thanks.

-Mahmudul

**Comment by nkuehnel** [comment]
Hi Mahmudul,

sorry for the late response. I think I found the issue and will fix it in a moment.

**Comment by nkuehnel** [comment]
@mhchayan could you update the code from master branch and try again?

**Comment by mhchayan** [comment]
Hi Nico, Thanks for the update. Still, I am trying to generate Synthetic Population, it is not finished yet. But the ClassCastException is not showing anymore. I appreciate your kind help.

**Comment by nkuehnel** [comment]
Great, I'm closing the issue for now, let us know if you need further help
