### ISSUE TITLE
PT travel times router needs links for dummy activities

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/silo#40]
SILO currently fails because the pt router recently implemented requires the dummy facilities to have links assigned. Dummy facilities are created in MatsimPtTravelTimes.java :

```
for (Node originNode : zoneCalculationNodesMap.get(origin)) { // Several points in a given origin zone
			for (Node destinationNode : zoneCalculationNodesMap.get(destination)) {// several points in a given destination zone
				ActivityFacilitiesFactory activityFacilitiesFactory = new ActivityFacilitiesFactoryImpl();
				ActivityFacility originFacility = activityFacilitiesFactory.createActivityFacility(null, originNode.getCoord());
				ActivityFacility destinationFacility = activityFacilitiesFactory.createActivityFacility(null, destinationNode.getCoord());
```

One solution would be to just take _ANY_ of the in-links of originNode and destinationNode, respectively. Would that affect the router a lot?
@dziemke ?

**Comment by nkuehnel** [comment]
```
java.lang.RuntimeException: java.lang.RuntimeException: fromLink missing.
	at de.tum.bgu.msm.SiloMatsim.run(SiloMatsim.java:50)
	at de.tum.bgu.msm.transportModel.matsim.SiloMatsimTest.testMain(SiloMatsimTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatchman$1.evaluate(TestWatchman.java:53)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: fromLink missing.
	at org.matsim.core.router.FreespeedFactorRoutingModule.routeLeg(FreespeedFactorRoutingModule.java:100)
	at org.matsim.core.router.FreespeedFactorRoutingModule.calcRoute(FreespeedFactorRoutingModule.java:73)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:183)
	at de.tum.bgu.msm.transportModel.matsim.MatsimPtTravelTimes.getTravelTimeFromTo(MatsimPtTravelTimes.java:73)
	at de.tum.bgu.msm.data.Accessibility.getTransitTravelTime(Accessibility.java:139)
	at de.tum.bgu.msm.data.Accessibility.calculateAccessibilities(Accessibility.java:170)
	at de.tum.bgu.msm.transportModel.matsim.MatsimTransportModel.runTransportModel(MatsimTransportModel.java:139)
	at de.tum.bgu.msm.SiloModel.runModel(SiloModel.java:125)
	at de.tum.bgu.msm.SiloMatsim.run(SiloMatsim.java:46)
	... 24 more
```

**Comment by nkuehnel** [comment]
2b00493 should work. as of now we're not going to use dynamic transit travel times anyway
